# Generated by Django 4.2.14 on 2026-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Token used in {{key}} placeholders (letters, digits, _)', max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('example', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('query', 'Query (auto-resolved from data)'), ('manual', 'Manual (admin enters per-campaign)')], max_length=10)),
                ('resolver_key', models.CharField(blank=True, help_text='Required when source=query; must match a registered resolver', max_length=80)),
                ('input_widget', models.CharField(choices=[('text', 'Text'), ('textarea', 'Multi-line text'), ('date', 'Date'), ('datetime', 'Date & Time'), ('url', 'URL')], default='text', help_text='Input type shown in compose when source=manual', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='extra_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='allocation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='project_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
