# Generated by Django 4.2.14 on 2026-04-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_notifications', '0002_notificationvariable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationvariable',
            name='value',
            field=models.TextField(blank=True, default='', help_text='Fixed value used for every campaign (manual variables only).'),
        ),
        migrations.AlterField(
            model_name='notificationvariable',
            name='input_widget',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Multi-line text'), ('date', 'Date'), ('datetime', 'Date & Time'), ('url', 'URL')], default='text', help_text='Input type for the Value field when source=manual', max_length=10),
        ),
    ]
