# Generated by Django 4.2.14 on 2026-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_notifications', '0003_notificationvariable_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='rendered_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='rendered_subject',
            field=models.TextField(blank=True, default=''),
        ),
    ]
