# Generated by Django 4.2.14 on 2026-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldfront_notifications', '0004_notificationlog_rendered_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationvariable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
